// <auto-generated />
using System;
using IQC.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IQC.Infrastructure.Data.Migrations
{
    [DbContext(typeof(IqcDbContext))]
    partial class IqcDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IQC.Domain.Entities.AuthSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccessTokenHash")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("refresh_token_hash");

                    b.Property<bool>("Revoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("RefreshTokenHash");

                    b.HasIndex("UserId");

                    b.ToTable("auth_sessions", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.BomProcess", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BomId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("bom_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("MachineGroupId")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductionTeamId")
                        .HasColumnType("longtext");

                    b.Property<int>("QuotaPerShift")
                        .HasColumnType("int");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("UnitOfMeasureId")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BomId", "SortOrder");

                    b.ToTable("bom_processes", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.DeviceLoginRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("IpAddress")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewedById")
                        .HasColumnType("longtext");

                    b.Property<string>("ReviewedByName")
                        .HasColumnType("longtext");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DeviceLoginRequests");
                });

            modelBuilder.Entity("IQC.Domain.Entities.EmployeeProductRate", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("RateVnd")
                        .HasColumnType("decimal(65,30)");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EmployeeProductRates");
                });

            modelBuilder.Entity("IQC.Domain.Entities.Group", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Lead")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LeadShort")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("lead_short");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.GroupMember", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("GroupId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsLead")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_lead");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("joined_at");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("group_members", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.Machine", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AccountingCode")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("accounting_code");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("MachineGroupId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductionTeamId")
                        .HasColumnType("longtext");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<string>("SpecsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("MachineGroupId");

                    b.HasIndex("Name");

                    b.ToTable("machines", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.MachineChangeRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BomId")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("FromMachine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrderId")
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequestedById")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequestedName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReviewNote")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewedById")
                        .HasColumnType("longtext");

                    b.Property<string>("ReviewedName")
                        .HasColumnType("longtext");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ToMachine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MachineChangeRequests");
                });

            modelBuilder.Entity("IQC.Domain.Entities.MachineGroup", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductionTeamId")
                        .HasColumnType("longtext");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("machine_groups", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.MachineIncident", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AssignedToId")
                        .HasColumnType("longtext");

                    b.Property<string>("AssignedToName")
                        .HasColumnType("longtext");

                    b.Property<string>("BomId")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrderId")
                        .HasColumnType("longtext");

                    b.Property<string>("ReportedById")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReportedByName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MachineIncidents");
                });

            modelBuilder.Entity("IQC.Domain.Entities.Notification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("Link")
                        .HasColumnType("longtext");

                    b.Property<bool>("Read")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Read", "CreatedAt");

                    b.ToTable("notifications", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.OrderAttachment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductionOrderId")
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("OrderAttachments");
                });

            modelBuilder.Entity("IQC.Domain.Entities.OrderAuditLog", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductionOrderId")
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("OrderAuditLogs");
                });

            modelBuilder.Entity("IQC.Domain.Entities.OrderBom", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AssignedGroupId")
                        .HasColumnType("longtext");

                    b.Property<string>("AssignedGroupName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AssignedWorkersJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("assigned_workers");

                    b.Property<string>("BomCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("bom_code");

                    b.Property<string>("CatalogBomId")
                        .HasColumnType("longtext")
                        .HasColumnName("catalog_bom_id");

                    b.Property<string>("CatalogProcessId")
                        .HasColumnType("longtext")
                        .HasColumnName("catalog_process_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<int>("FailQty")
                        .HasColumnType("int");

                    b.Property<string>("Machine")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaterialSpecsJson")
                        .HasColumnType("json")
                        .HasColumnName("material_specs");

                    b.Property<string>("PartCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PartName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("part_name");

                    b.Property<int>("PassQty")
                        .HasColumnType("int");

                    b.Property<string>("Process")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductionOrderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("production_order_id");

                    b.Property<string>("RawMaterial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("row_version");

                    b.Property<string>("SpecColsJson")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("spec_cols");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetQty")
                        .HasColumnType("int");

                    b.Property<string>("TechNote")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("Status");

                    b.HasIndex("ProductionOrderId", "BomCode")
                        .IsUnique();

                    b.ToTable("boms", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.PartBom", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<string>("SemiProductId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("semi_product_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SemiProductId");

                    b.ToTable("part_boms", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("row_version");

                    b.Property<string>("UnitOfMeasureId")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.ProductAttachment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContentBase64")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttachment");
                });

            modelBuilder.Entity("IQC.Domain.Entities.ProductionOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("Customer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Deadline")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("order_no");

                    b.Property<bool>("PendingApproval")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("pending_approval");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("ProductId")
                        .HasColumnType("longtext");

                    b.Property<string>("ProductLine")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("product_line");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("row_version");

                    b.Property<string>("Shift")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TargetQty")
                        .HasColumnType("int")
                        .HasColumnName("target_qty");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("OrderNo")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Status", "CreatedAt");

                    b.ToTable("production_orders", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.QcReport", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BomId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<int>("FailQty")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PassQty")
                        .HasColumnType("int");

                    b.Property<bool>("Passed")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<string>("SubmittedById")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BomId")
                        .IsUnique();

                    b.ToTable("QcReports");
                });

            modelBuilder.Entity("IQC.Domain.Entities.Role", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.SemiProduct", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Active")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("DrawingId")
                        .HasColumnType("longtext");

                    b.Property<string>("MeasurementSpecsJson")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("measurement_specs");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("product_id");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<string>("UnitOfMeasureId")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("WeightKg")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("Name");

                    b.HasIndex("ProductId");

                    b.ToTable("semi_products", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.SemiProductAttachment", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ContentBase64")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<string>("SemiProductId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("SemiProductId");

                    b.ToTable("SemiProductAttachment");
                });

            modelBuilder.Entity("IQC.Domain.Entities.ShiftClose", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BomId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("bom_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<int>("FailQty")
                        .HasColumnType("int");

                    b.Property<string>("HistoryJson")
                        .HasColumnType("json")
                        .HasColumnName("history");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("order_id");

                    b.Property<int>("PassQty")
                        .HasColumnType("int");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("row_version");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("worker_id");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BomId");

                    b.HasIndex("OrderId");

                    b.HasIndex("Status");

                    b.HasIndex("WorkerId");

                    b.HasIndex("OrderId", "BomId", "WorkerId");

                    b.ToTable("shift_closes", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.ShiftUnlockRequest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BomId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ReviewedById")
                        .HasColumnType("longtext");

                    b.Property<string>("ReviewedName")
                        .HasColumnType("longtext");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ShiftUnlockRequests");
                });

            modelBuilder.Entity("IQC.Domain.Entities.TeamSummary", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BomId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<int>("FailQty")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("PassQty")
                        .HasColumnType("int");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<string>("SubmittedById")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SubmittedByName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BomId")
                        .IsUnique();

                    b.ToTable("TeamSummaries");
                });

            modelBuilder.Entity("IQC.Domain.Entities.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("employee_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Active");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("GrantedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("granted_at");

                    b.Property<string>("GrantedBy")
                        .HasColumnType("longtext")
                        .HasColumnName("granted_by");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.WarehouseMovement", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<int>("Delta")
                        .HasColumnType("int");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ItemKind")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("QtyAfter")
                        .HasColumnType("int");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("WarehouseMovements");
                });

            modelBuilder.Entity("IQC.Domain.Entities.WarehouseStock", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemKind")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("item_kind");

                    b.Property<int>("Qty")
                        .HasColumnType("int");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasDefaultValue(0u)
                        .HasColumnName("row_version");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId", "ItemKind", "ItemId")
                        .IsUnique();

                    b.ToTable("warehouse_stocks", (string)null);
                });

            modelBuilder.Entity("IQC.Domain.Entities.WorkerEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BomId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BomId");

                    b.ToTable("WorkerEntries");
                });

            modelBuilder.Entity("IQC.Domain.Entities.WorkerEntryRow", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedByName")
                        .HasColumnType("longtext");

                    b.Property<string>("DimsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EntryId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NgoaiQuan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<uint>("RowVersion")
                        .HasColumnType("int unsigned");

                    b.Property<int>("Tt")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedById")
                        .HasColumnType("longtext");

                    b.Property<string>("UpdatedByName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EntryId");

                    b.ToTable("WorkerEntryRows");
                });

            modelBuilder.Entity("IQC.Domain.Entities.BomProcess", b =>
                {
                    b.HasOne("IQC.Domain.Entities.PartBom", "Bom")
                        .WithMany("Processes")
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bom");
                });

            modelBuilder.Entity("IQC.Domain.Entities.GroupMember", b =>
                {
                    b.HasOne("IQC.Domain.Entities.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IQC.Domain.Entities.User", "User")
                        .WithMany("GroupMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IQC.Domain.Entities.Machine", b =>
                {
                    b.HasOne("IQC.Domain.Entities.MachineGroup", "MachineGroup")
                        .WithMany("Machines")
                        .HasForeignKey("MachineGroupId");

                    b.Navigation("MachineGroup");
                });

            modelBuilder.Entity("IQC.Domain.Entities.OrderAttachment", b =>
                {
                    b.HasOne("IQC.Domain.Entities.ProductionOrder", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ProductionOrderId");
                });

            modelBuilder.Entity("IQC.Domain.Entities.OrderAuditLog", b =>
                {
                    b.HasOne("IQC.Domain.Entities.ProductionOrder", null)
                        .WithMany("AuditLogs")
                        .HasForeignKey("ProductionOrderId");
                });

            modelBuilder.Entity("IQC.Domain.Entities.OrderBom", b =>
                {
                    b.HasOne("IQC.Domain.Entities.ProductionOrder", "ProductionOrder")
                        .WithMany("Boms")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("IQC.Domain.Entities.PartBom", b =>
                {
                    b.HasOne("IQC.Domain.Entities.SemiProduct", "SemiProduct")
                        .WithMany("Boms")
                        .HasForeignKey("SemiProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SemiProduct");
                });

            modelBuilder.Entity("IQC.Domain.Entities.ProductAttachment", b =>
                {
                    b.HasOne("IQC.Domain.Entities.Product", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IQC.Domain.Entities.QcReport", b =>
                {
                    b.HasOne("IQC.Domain.Entities.OrderBom", "Bom")
                        .WithOne("QcReport")
                        .HasForeignKey("IQC.Domain.Entities.QcReport", "BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bom");
                });

            modelBuilder.Entity("IQC.Domain.Entities.SemiProduct", b =>
                {
                    b.HasOne("IQC.Domain.Entities.Product", "Product")
                        .WithMany("SemiProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IQC.Domain.Entities.SemiProductAttachment", b =>
                {
                    b.HasOne("IQC.Domain.Entities.SemiProduct", null)
                        .WithMany("Attachments")
                        .HasForeignKey("SemiProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IQC.Domain.Entities.TeamSummary", b =>
                {
                    b.HasOne("IQC.Domain.Entities.OrderBom", "Bom")
                        .WithOne("TeamSummary")
                        .HasForeignKey("IQC.Domain.Entities.TeamSummary", "BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bom");
                });

            modelBuilder.Entity("IQC.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("IQC.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IQC.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IQC.Domain.Entities.WorkerEntry", b =>
                {
                    b.HasOne("IQC.Domain.Entities.OrderBom", "Bom")
                        .WithMany("WorkerEntries")
                        .HasForeignKey("BomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bom");
                });

            modelBuilder.Entity("IQC.Domain.Entities.WorkerEntryRow", b =>
                {
                    b.HasOne("IQC.Domain.Entities.WorkerEntry", "Entry")
                        .WithMany("Rows")
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("IQC.Domain.Entities.Group", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("IQC.Domain.Entities.MachineGroup", b =>
                {
                    b.Navigation("Machines");
                });

            modelBuilder.Entity("IQC.Domain.Entities.OrderBom", b =>
                {
                    b.Navigation("QcReport");

                    b.Navigation("TeamSummary");

                    b.Navigation("WorkerEntries");
                });

            modelBuilder.Entity("IQC.Domain.Entities.PartBom", b =>
                {
                    b.Navigation("Processes");
                });

            modelBuilder.Entity("IQC.Domain.Entities.Product", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("SemiProducts");
                });

            modelBuilder.Entity("IQC.Domain.Entities.ProductionOrder", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("AuditLogs");

                    b.Navigation("Boms");
                });

            modelBuilder.Entity("IQC.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("IQC.Domain.Entities.SemiProduct", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Boms");
                });

            modelBuilder.Entity("IQC.Domain.Entities.User", b =>
                {
                    b.Navigation("GroupMembers");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("IQC.Domain.Entities.WorkerEntry", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
